const price = 4;
const currencyData=
    [
        {
            "id": "USD",
            "symbol": "$",
            "name": "US Dollar",
            "symbol_native": "$",
            "code": "USD",
            "name_plural": "US dollars",
            "flag": "http://flags.fmcdn.net/data/flags/normal/us.png",
            "color":"red"
        },
        {
            "id": "CAD",
            "symbol": "CA$",
            "name": "Canadian Dollar",
            "symbol_native": "$",
            "code": "CAD",
            "name_plural": "Canadian dollars",
            "flag": 'http://flags.fmcdn.net/data/flags/normal/ca.png',
            "color":"red"
        },
        {
            "id": "EUR",
            "symbol": "€",
            "name": "Euro",
            "symbol_native": "€",
            "code": "EUR",
            "name_plural": "euros",
            "flag": './7aa757c532b0a752236021195bd5a45d.jpeg',
            "color":"blue"
        },
        {
            "ID":"AED",
            "symbol": "AED",
            "name": "United Arab Emirates Dirham",
            "symbol_native": "د.إ.‏",
            "code": "AED",
            "name_plural": "UAE dirhams",
            "flag": 'http://flags.fmcdn.net/data/flags/normal/ae.png',
            "color":"white"
        },
        {
            "id": "AFN",
            "symbol": "Af",
            "name": "Afghan Afghani",
            "symbol_native": "؋",
            "code": "AFN",
            "name_plural": "Afghan Afghanis",
            "flag": 'http://flags.fmcdn.net/data/flags/normal/af.png',
            "color":"red",
        },
        {
        "id": "ALL",
        "symbol": "ALL",
        "name": "Albanian Lek",
        "symbol_native": "Lek",
        "code": "ALL",
        "name_plural": "Albanian lekë",
        "flag": 'http://flags.fmcdn.net/data/flags/normal/al.png',
        "color":"red",
        },
        {
        "id":"AMD",
        "symbol": "AMD",
        "name": "Armenian Dram",
        "symbol_native": "դր.",
        "code": "AMD",
        "name_plural": "Armenian drams",
        "flag": "http://flags.fmcdn.net/data/flags/normal/am.png",
        "color":"red"
        },

        {"id":"ARS",
        "symbol": "AR$",
        "name": "Argentine Peso",
        "symbol_native": "$",
        "code": "ARS",
        "name_plural": "Argentine pesos",
        "flag": "http://flags.fmcdn.net/data/flags/normal/ar.png",
        "color":"ligt-blue"
},
        {
        "id":"AUD" ,
        "symbol": "AU$",
        "name": "Australian Dollar",
        "symbol_native": "$",
        "code": "AUD",
        "name_plural": "Australian dollars",
        "flag": 'http://flags.fmcdn.net/data/flags/normal/au.png',
        "color":"blue"
},
        {
        "id":"AZN" ,
        "symbol": "man.",
        "name": "Azerbaijani Manat",
        "symbol_native": "ман.",
        "code": "AZN",
        "name_plural": "Azerbaijani manats",
        "flag": "http://flags.fmcdn.net/data/flags/normal/az.png",
        "color":"light-blue"
},
        {
        "id":"BAM" ,
        "symbol": "KM",
        "name": "Bosnia-Herzegovina Convertible Mark",
        "symbol_native": "KM",
        "code": "BAM",
        "name_plural": "Bosnia-Herzegovina convertible marks",
        "flag": "http://flags.fmcdn.net/data/flags/normal/ba.png",
        "color":"blue"
},
        {
        "id":"BDT" ,
        "symbol": "Tk",
        "name": "Bangladeshi Taka",
        "symbol_native": "৳",
        "code": "BDT",
        "name_plural": "Bangladeshi takas",
        "flag": "http://flags.fmcdn.net/data/flags/normal/bd.png",
        "color":"blue"
},
        {
        "id":"BGN" ,
        "symbol": "BGN",
        "name": "Bulgarian Lev",
        "symbol_native": "лв.",
        "code": "BGN",
        "name_plural": "Bulgarian leva",
        "flag": 'http://flags.fmcdn.net/data/flags/normal/bg.png',
        "color":"green"
},{
        "id":"BHD" ,
        "symbol": "BD",
        "name": "Bahraini Dinar",
        "symbol_native": "د.ب.‏",
        "code": "BHD",
        "name_plural": "Bahraini dinars",
        "flag": 'http://flags.fmcdn.net/data/flags/normal/bh.png',
        "color":"red"
},{
        "id":"BIF" ,
        "symbol": "FBu",
        "name": "Burundian Franc",
        "symbol_native": "FBu",
        "code": "BIF",
        "name_plural": "Burundian francs",
        "flag": 'http://flags.fmcdn.net/data/flags/normal/bi.png',
        "color":"red"
},{
        "id":"BND" ,
        "symbol": "BN$",
        "name": "Brunei Dollar",
        "symbol_native": "$",
        "code": "BND",
        "name_plural": "Brunei dollars",
        "flag": "http://flags.fmcdn.net/data/flags/normal/bn.png",
        "color":"yellow"
},{
        "id":"BOB" ,
        "symbol": "Bs",
        "name": "Bolivian Boliviano",
        "symbol_native": "Bs",
        "code": "BOB",
        "name_plural": "Bolivian bolivianos",
        "flag": "http://flags.fmcdn.net/data/flags/normal/bo.png",
        "color":"yellow"
},{
        "id":"BRL" ,
        "symbol": "R$",
        "name": "Brazilian Real",
        "symbol_native": "R$",
        "flag": "http://flags.fmcdn.net/data/flags/normal/br.png",
        "code": "BRL",
        "name_plural": "Brazilian reals",
        "color":"green"
},{
        "id":"BWP" ,
        "symbol": "BWP",
        "name": "Botswanan Pula",
        "symbol_native": "P",
        "code": "BWP",
        "name_plural": "Botswanan pulas",
        "flag": "http://flags.fmcdn.net/data/flags/normal/bw.png",
        "color":"ligt-blue"
},{
        "BYR":"BYR" ,
        "symbol": "BYR",
        "name": "Belarusian Ruble",
        "symbol_native": "BYR",
        "code": "BYR",
        "name_plural": "Belarusian rubles",
        "flag": "http://flags.fmcdn.net/data/flags/normal/ru.png",
        "color":"blue"
},{
        "id":"BZD" ,
        "symbol": "BZ$",
        "name": "Belize Dollar",
        "symbol_native": "$",
        "code": "BZD",
        "name_plural": "Belize dollars",
        "flag": "http://flags.fmcdn.net/data/flags/normal/bz.png",
        "color":"blue"
},{
        "id":"CDF" ,
        "symbol": "CDF",
        "name": "Congolese Franc",
        "symbol_native": "FrCD",
        "code": "CDF",
        "name_plural": "Congolese francs",
        "flag": "http://flags.fmcdn.net/data/flags/normal/dk.png",
        "color":"red"
},{
        "id":"CHF" ,
        "symbol": "CHF",
        "name": "Swiss Franc",
        "symbol_native": "CHF",
        "code": "CHF",
        "name_plural": "Swiss francs",
        "flag": "http://flags.fmcdn.net/data/flags/normal/ch.png",
        "color":"red"
},{
        "id":"CLP" ,
        "symbol": "CL$",
        "name": "Chilean Peso",
        "symbol_native": "$",
        "code": "CLP",
        "name_plural": "Chilean pesos",
        "flag": "http://flags.fmcdn.net/data/flags/normal/cl.png",
        "color":"red"
},
{
        "id":"CNY",
        "symbol": "CN¥",
        "name": "Chinese Yuan",
        "symbol_native": "CN¥",
        "code": "CNY",
        "name_plural": "Chinese yuan",
        "flag": "http://flags.fmcdn.net/data/flags/normal/cn.png",
        "color":"red"
},
{
        "id":"COP" ,
        "symbol": "CO$",
        "name": "Colombian Peso",
        "symbol_native": "$",
        "code": "COP",
        "name_plural": "Colombian pesos",
        "flag":  "http://flags.fmcdn.net/data/flags/normal/co.png",
        "color":"yellow"
},{
        "id":"CRC" ,
        "symbol": "₡",
        "name": "Costa Rican Colón",
        "symbol_native": "₡",
        "code": "CRC",
        "name_plural": "Costa Rican colóns",
        "flag": 'http://flags.fmcdn.net/data/flags/normal/cr.png',
        "color":"blue"
},{
         "id":"CVE" ,
        "symbol": "CV$",
        "name": "Cape Verdean Escudo",
        "symbol_native": "CV$",
        "code": "CVE",
        "name_plural": "Cape Verdean escudos",
        "flag": 'http://flags.fmcdn.net/data/flags/normal/cv.png',
        "color":"blue"
},{
        "id":"CZK" ,
        "symbol": "Kč",
        "name": "Czech Republic Koruna",
        "symbol_native": "Kč",
        "code": "CZK",
        "name_plural": "Czech Republic korunas",
        "flag": 'http://flags.fmcdn.net/data/flags/normal/cz.png',
        "color":"red"
},{
        "id":"DJF" ,
        "symbol": "Fdj",
        "name": "Djiboutian Franc",
        "symbol_native": "Fdj",
        "code": "DJF",
        "name_plural": "Djiboutian francs",
        "flag": "http://flags.fmcdn.net/data/flags/normal/dj.png",
        "color":"green"
},{
        "DKK":"DKK" ,
        "symbol": "Dkr",
        "name": "Danish Krone",
        "symbol_native": "kr",
        "code": "DKK",
        "name_plural": "Danish kroner",
        "flag": 'http://flags.fmcdn.net/data/flags/normal/do.png',
        "color":"blue"
},{
        "id":"DOP" ,
        "symbol": "RD$",
        "name": "Dominican Peso",
        "symbol_native": "RD$",
        "code": "DOP",
        "name_plural": "Dominican pesos",
        "flag": 'http://flags.fmcdn.net/data/flags/normal/dm.png',
        "color":"green"
},{
        "id":"DZD" ,
        "symbol": "DA",
        "name": "Algerian Dinar",
        "symbol_native": "د.ج.‏",
        "code": "DZD",
        "name_plural": "Algerian dinars",
        "flag": 'http://flags.fmcdn.net/data/flags/normal/dz.png',
        "color":"green"
},{
        "id":"EEK" ,
        "symbol": "Ekr",
        "name": "Estonian Kroon",
        "symbol_native": "kr",
        "code": "EEK",
        "name_plural": "Estonian kroons",
        "flag": "http://flags.fmcdn.net/data/flags/normal/ee.png",
        "color":"blue"
},{
        "id":"EGP" ,
        "symbol": "EGP",
        "name": "Egyptian Pound",
        "symbol_native": "ج.م.‏",
        "code": "EGP",
        "name_plural": "Egyptian pounds",
        "flag": 'http://flags.fmcdn.net/data/flags/normal/eg.png',
        "color":"red"
},
{
        "id":"ERN",
        "symbol": "Nfk",
        "name": "Eritrean Nakfa",
        "symbol_native": "Nfk",
        "code": "ERN",
        "name_plural": "Eritrean nakfas",
        "flag": 'http://flags.fmcdn.net/data/flags/normal/er.png',
        "color":"red"
},
{
        "id":"ETB",
        "symbol": "Br",
        "name": "Ethiopian Birr",
        "symbol_native": "Br",
        "code": "ETB",
        "name_plural": "Ethiopian birrs",
        "flag": 'http://flags.fmcdn.net/data/flags/normal/et.png',
        "color":"green"
},
{
        "id":"GBP",
        "symbol": "£",
        "name": "British Pound Sterling",
        "symbol_native": "£",
        "code": "GBP",
        "name_plural": "British pounds sterling",
        "flag": 'http://flags.fmcdn.net/data/flags/normal/gb.png',
        "color":"blue"
},
{
        "GEL":"GEL",
        "symbol": "GEL",
        "name": "Georgian Lari",
        "symbol_native": "GEL",
        "code": "GEL",
        "name_plural": "Georgian laris",
        "flag": "http://flags.fmcdn.net/data/flags/normal/ge.png",
        "color":"white"
},
{
        "id":"GHS",
        "symbol": "GH₵",
        "name": "Ghanaian Cedi",
        "symbol_native": "GH₵",
        "code": "GHS",
        "name_plural": "Ghanaian cedis",
        "flag": 'http://flags.fmcdn.net/data/flags/normal/gh.png',
        "color":"red"
},
{
        "id":"GNF",
        "symbol": "FG",
        "name": "Guinean Franc",
        "symbol_native": "FG",
        "code": "GNF",
        "name_plural": "Guinean francs",
        "flag": 'http://flags.fmcdn.net/data/flags/normal/gq.png',
        "color":"green"
},
{
        "id":"GTQ",
        "symbol": "GTQ",
        "name": "Guatemalan Quetzal",
        "symbol_native": "Q",
        "code": "GTQ",
        "name_plural": "Guatemalan quetzals",
        "flag": "http://flags.fmcdn.net/data/flags/normal/gt.png",
        "color":"light-blue"
},
{
        "id":"HKD",
        "symbol": "HK$",
        "name": "Hong Kong Dollar",
        "symbol_native": "$",
        "code": "HKD",
        "name_plural": "Hong Kong dollars",
        "flag": "http://flags.fmcdn.net/data/flags/normal/cn.png",
        "color":"red"
},
{
        "id":"HNL",
        "symbol": "HNL",
        "name": "Honduran Lempira",
        "symbol_native": "L",
        "code": "HNL",
        "name_plural": "Honduran lempiras",
        "flag": "http://flags.fmcdn.net/data/flags/normal/hn.png",
        "color": "blue"
},
{
        "id":"HRK",
        "symbol": "kn",
        "name": "Croatian Kuna",
        "symbol_native": "kn",
        "code": "HRK",
        "name_plural": "Croatian kunas",
        "flag": "http://flags.fmcdn.net/data/flags/normal/hr.png",
        "color":"red"
},
{
        "id":"HUF",
        "symbol": "Ft",
        "name": "Hungarian Forint",
        "symbol_native": "Ft",
        "code": "HUF",
        "name_plural": "Hungarian forints",
        "flag": "http://flags.fmcdn.net/data/flags/normal/hu.png",
        "color":"green"
},
{
        "id":"IDR",
        "symbol": "Rp",
        "name": "Indonesian Rupiah",
        "symbol_native": "Rp",
        "code": "IDR",
        "name_plural": "Indonesian rupiahs",
        "flag": "http://flags.fmcdn.net/data/flags/normal/id.png",
        "color" :"red"
},
{
        "id":"ILS",
        "symbol": "₪",
        "name": "Israeli New Sheqel",
        "symbol_native": "₪",
        "code": "ILS",
        "name_plural": "Israeli new sheqels",
        "flag":  "http://flags.fmcdn.net/data/flags/normal/il.png",
        "color":"white"
},
{
        "id":"INR",
        "symbol": "Rs",
        "name": "Indian Rupee",
        "symbol_native": "টকা",
        "code": "INR",
        "name_plural": "Indian rupees",
        "flag": "http://flags.fmcdn.net/data/flags/normal/in.png",
        "color":"orange"
},
{
        "id":"IQD",
        "symbol": "IQD",
        "name": "Iraqi Dinar",
        "symbol_native": "د.ع.‏",
        "code": "IQD",
        "name_plural": "Iraqi dinars",
        "flag": "http://flags.fmcdn.net/data/flags/normal/iq.png",
        "color" :"red"
},
{
        "id":"IRR",
        "symbol": "IRR",
        "name": "Iranian Rial",
        "symbol_native": "﷼",
        "code": "IRR",
        "name_plural": "Iranian rials",
        "flag": "http://flags.fmcdn.net/data/flags/normal/ir.png",
        "color" :"red"
},
{
        "id":"ISK",
        "symbol": "Ikr",
        "name": "Icelandic Króna",
        "symbol_native": "kr",
        "code": "ISK",
        "name_plural": "Icelandic krónur",
        "flag": "http://flags.fmcdn.net/data/flags/normal/is.png",
        "color" :"blue"
},
{
        "id":"JMD",
        "symbol": "J$",
        "name": "Jamaican Dollar",
        "symbol_native": "$",
        "code": "JMD",
        "name_plural": "Jamaican dollars",
        "flag": "http://flags.fmcdn.net/data/flags/normal/jm.png",
        "color" :"green"
},
{
        "id":"JOD",
        "symbol": "JD",
        "name": "Jordanian Dinar",
        "symbol_native": "د.أ.‏",
        "code": "JOD",
        "name_plural": "Jordanian dinars",
        "flag": "http://flags.fmcdn.net/data/flags/normal/jo.png",
        "color" :"green"
},
{
        "id":"JPY",
        "symbol": "¥",
        "name": "Japanese Yen",
        "symbol_native": "￥",
        "code": "JPY",
        "name_plural": "Japanese yen",
        "flag": "http://flags.fmcdn.net/data/flags/normal/jp.png",
        "color" :"white"
},
{
        "id":"KES",
        "symbol": "Ksh",
        "name": "Kenyan Shilling",
        "symbol_native": "Ksh",
        "code": "KES",
        "name_plural": "Kenyan shillings",
        "flag": "http://flags.fmcdn.net/data/flags/normal/ke.png",
        "color" :"green"
},
{
        "id":"KHR",
        "symbol": "KHR",
        "name": "Cambodian Riel",
        "symbol_native": "៛",
        "code": "KHR",
        "name_plural": "Cambodian riels",
        "flag": "http://flags.fmcdn.net/data/flags/normal/kh.png",
        "color" :"blue"
},
{
        "id":"KMF",
        "symbol": "CF",
        "name": "Comorian Franc",
        "symbol_native": "FC",
        "code": "KMF",
        "name_plural": "Comorian francs",
        "flag": "http://flags.fmcdn.net/data/flags/normal/km.png",
        "color":"green"
},
{
        "id":"KRW",
        "symbol": "₩",
        "name": "South Korean Won",
        "symbol_native": "₩",
        "code": "KRW",
        "name_plural": "South Korean won",
        "flag": "http://flags.fmcdn.net/data/flags/normal/kr.png",
        "color":"white"
},
{
        "id":"KWD",
        "symbol": "KD",
        "name": "Kuwaiti Dinar",
        "symbol_native": "د.ك.‏",
        "code": "KWD",
        "name_plural": "Kuwaiti dinars",
        "flag": "http://flags.fmcdn.net/data/flags/normal/kw.png",
        "color": "red"
},
{
        "id":"KZT",
        "symbol": "KZT",
        "name": "Kazakhstani Tenge",
        "symbol_native": "тңг.",
        "code": "KZT",
        "name_plural": "Kazakhstani tenges",
        "flag": "http://flags.fmcdn.net/data/flags/normal/kz.png",
        "color":"light-blue"
},
{
    "id":"LBP",
    "symbol": "LB£",
        "name": "Lebanese Pound",
        "symbol_native": "ل.ل.‏",
        "code": "LBP",
        "name_plural": "Lebanese pounds",
        "flag": "http://flags.fmcdn.net/data/flags/normal/lb.png" ,
        "color":"red"
},
{
        "id":"LKR",
        "symbol": "SLRs",
        "name": "Sri Lankan Rupee",
        "symbol_native": "SL Re",
        "code": "LKR",
        "name_plural": "Sri Lankan rupees",
        "flag": "http://flags.fmcdn.net/data/flags/normal/lk.png",
        "color":"yellow"
},
{
        "id":"LTL",
        "symbol": "Lt",
        "name": "Lithuanian Litas",
        "symbol_native": "Lt",
        "code": "LTL",
        "name_plural": "Lithuanian litai",
        "flag": "http://flags.fmcdn.net/data/flags/normal/lt.png",
        "color":"yellow"
},
{
        "id":"LVL",
        "symbol": "Ls",
        "name": "Latvian Lats",
        "symbol_native": "Ls",
        "code": "LVL",
        "name_plural": "Latvian lati",
        "flag": "http://flags.fmcdn.net/data/flags/normal/lv.png",
        "color":"red"
},
{
        "id":"LYD",
        "symbol": "LD",
        "name": "Libyan Dinar",
        "symbol_native": "د.ل.‏",
        "code": "LYD",
        "name_plural": "Libyan dinars",
        "flag": "http://flags.fmcdn.net/data/flags/normal/ly.png",
        "color":"red"
},
{
        "id":"MAD",
        "symbol": "MAD",
        "name": "Moroccan Dirham",
        "symbol_native": "د.م.‏",
        "code": "MAD",
        "name_plural": "Moroccan dirhams",
        "flag": "http://flags.fmcdn.net/data/flags/normal/ma.png",
        "color":"red"
},
{
        "id":"MDL",
        "symbol": "MDL",
        "name": "Moldovan Leu",
        "symbol_native": "MDL",
        "code": "MDL",
        "name_plural": "Moldovan lei",
        "flag": "http://flags.fmcdn.net/data/flags/normal/md.png",
        "color":"yellow"
},
{
        "id":"MGA",
        "symbol": "MGA",
        "name": "Malagasy Ariary",
        "symbol_native": "MGA",
        "code": "MGA",
        "name_plural": "Malagasy Ariaries",
        "flag": "http://flags.fmcdn.net/data/flags/normal/mg.png",
        "color":"red"
},
{
        "id":"MKD",
        "symbol": "MKD",
        "name": "Macedonian Denar",
        "symbol_native": "MKD",
        "code": "MKD",
        "name_plural": "Macedonian denari",
        "flag": "http://flags.fmcdn.net/data/flags/normal/mk.png",
        "color": "red"
},
{
        "id":"MMK" ,
        "symbol": "MMK",
        "name": "Myanma Kyat",
        "symbol_native": "K",
        "code": "MMK",
        "name_plural": "Myanma kyats",
        "flag": "http://flags.fmcdn.net/data/flags/normal/mm.png",
        "color":"yellow"
},
{
        "id":"MOP" ,
        "symbol": "MOP$",
        "name": "Macanese Pataca",
        "symbol_native": "MOP$",
        "code": "MOP",
        "name_plural": "Macanese patacas",
        "flag": "http://flags.fmcdn.net/data/flags/normal/cn.png",
        "color":"red"
},
{
        "id":"MUR" ,
        "symbol": "MURs",
        "name": "Mauritian Rupee",
        "symbol_native": "MURs",
        "code": "MUR",
        "name_plural": "Mauritian rupees",
        "flag": "http://flags.fmcdn.net/data/flags/normal/mu.png",
        "color":"red"
},
{
        "id":"MXN" ,
        "symbol": "MX$",
        "name": "Mexican Peso",
        "symbol_native": "$",
        "code": "MXN",
        "name_plural": "Mexican pesos",
        "flag": "http://flags.fmcdn.net/data/flags/normal/mx.png",
        "color": "green"
},
{
        "id":"MYR" ,
        "symbol": "RM",
        "name": "Malaysian Ringgit",
        "symbol_native": "RM",
        "code": "MYR",
        "name_plural": "Malaysian ringgits",
        "flag": "http://flags.fmcdn.net/data/flags/normal/my.png",
        "color":"red"
},
{
        "id":"MZN" ,
        "symbol": "MTn",
        "name": "Mozambican Metical",
        "symbol_native": "MTn",
        "code": "MZN",
        "name_plural": "Mozambican meticals",
        "flag": "http://flags.fmcdn.net/data/flags/normal/mz.png",
        "color":"yellow"
},
{
        "id":"NAD" ,
        "symbol": "N$",
        "name": "Namibian Dollar",
        "symbol_native": "N$",
        "code": "NAD",
        "name_plural": "Namibian dollars",
        "flag": "http://flags.fmcdn.net/data/flags/normal/na.png",
        "color":"red"
},
{
        "id":"NGN" ,
        "symbol": "₦",
        "name": "Nigerian Naira",
        "symbol_native": "₦",
        "code": "NGN",
        "name_plural": "Nigerian nairas",
        "flag": "http://flags.fmcdn.net/data/flags/normal/ng.png",
        "color":"green"
},
{
        "id":"NIO" ,
        "symbol": "C$",
        "name": "Nicaraguan Córdoba",
        "symbol_native": "C$",
        "code": "NIO",
        "name_plural": "Nicaraguan córdobas",
        "flag": "http://flags.fmcdn.net/data/flags/normal/ni.png",
        "color":"blue"
},
{
        "id":"NOK" ,
        "symbol": "Nkr",
        "name": "Norwegian Krone",
        "symbol_native": "kr",
        "code": "NOK",
        "name_plural": "Norwegian kroner",
        "flag": "http://flags.fmcdn.net/data/flags/normal/no.png",
        "color":"red"
},
{
        "id":"NPR" ,
        "symbol": "NPRs",
        "name": "Nepalese Rupee",
        "symbol_native": "नेरू",
        "code": "NPR",
        "name_plural": "Nepalese rupees",
        "flag": "http://flags.fmcdn.net/data/flags/normal/np.png",
        "color":"white"
},
{
        "id":"NZD" ,
        "symbol": "NZ$",
        "name": "New Zealand Dollar",
        "symbol_native": "$",
        "code": "NZD",
        "name_plural": "New Zealand dollars",
        "flag": "http://flags.fmcdn.net/data/flags/normal/nz.png",
        "color":"blue"
},
{
        "id":"OMR" ,
        "symbol": "OMR",
        "name": "Omani Rial",
        "symbol_native": "ر.ع.‏",
        "code": "OMR",
        "name_plural": "Omani rials",
        "flag": "http://flags.fmcdn.net/data/flags/normal/om.png",
        "color":"red"
},
{
        "id":"PAB" ,
        "symbol": "B/.",
        "name": "Panamanian Balboa",
        "symbol_native": "B/.",
        "code": "PAB",
        "name_plural": "Panamanian balboas",
        "flag": "http://flags.fmcdn.net/data/flags/normal/pa.png",
        "color":"white"
},
{
        "id":"PEN" ,
        "symbol": "S/.",
        "name": "Peruvian Nuevo Sol",
        "symbol_native": "S/.",
        "code": "PEN",
        "name_plural": "Peruvian nuevos soles",
        "flag": "http://flags.fmcdn.net/data/flags/normal/pe.png" ,
        "color":"red"
},
{
        "id":"PHP" ,
        "symbol": "₱",
        "name": "Philippine Peso",
        "symbol_native": "₱",
        "code": "PHP",
        "name_plural": "Philippine pesos",
        "flag": "http://flags.fmcdn.net/data/flags/normal/ph.png",
        "color":"blue"
},
{
        "id":"PKR" ,
        "symbol": "PKRs",
        "name": "Pakistani Rupee",
        "symbol_native": "₨",
        "code": "PKR",
        "name_plural": "Pakistani rupees",
        "flag": "http://flags.fmcdn.net/data/flags/normal/pk.png",
        "color":"green"
},
{
        "id": "PLN" ,
        "symbol": "zł",
        "name": "Polish Zloty",
        "symbol_native": "zł",
        "code": "PLN",
        "name_plural": "Polish zlotys",
        "flag": "http://flags.fmcdn.net/data/flags/normal/pl.png",
        "color":"red"
},
{
        "id":"PYG" ,
        "symbol": "₲",
        "name": "Paraguayan Guarani",
        "symbol_native": "₲",
        "code": "PYG",
        "name_plural": "Paraguayan guaranis",
        "flag": "http://flags.fmcdn.net/data/flags/normal/py.png",
        "color":"red"
},
{
        "id":"QAR" ,
        "symbol": "QR",
        "name": "Qatari Rial",
        "symbol_native": "ر.ق.‏",
        "code": "QAR",
        "name_plural": "Qatari rials",
        "flag": "http://flags.fmcdn.net/data/flags/normal/qa.png",
        "color":"red"
},
{
        "id":"RON" ,
        "symbol": "RON",
        "name": "Romanian Leu",
        "symbol_native": "RON",
        "code": "RON",
        "name_plural": "Romanian lei",
        "flag": "http://flags.fmcdn.net/data/flags/normal/ro.png",
        "color":"red"
},
{
        "id":"RSD" ,
        "symbol": "din.",
        "name": "Serbian Dinar",
        "symbol_native": "дин.",
        "code": "RSD",
        "name_plural": "Serbian dinars",
        "flag": "http://flags.fmcdn.net/data/flags/normal/rs.png",
        "color":"red"
},
{
        "id":"RUB" ,
        "symbol": "RUB",
        "name": "Russian Ruble",
        "symbol_native": "руб.",
        "code": "RUB",
        "name_plural": "Russian rubles",
        "flag": "http://flags.fmcdn.net/data/flags/normal/ru.png",
        "color":"blue"
},
{
        "id":"RWF" ,
        "symbol": "RWF",
        "name": "Rwandan Franc",
        "symbol_native": "FR",
        "code": "RWF",
        "name_plural": "Rwandan francs",
        "flag": "http://flags.fmcdn.net/data/flags/normal/rw.png",
        "color":"light-blue"
},
{
        "id":"SAR",
        "symbol": "SR",
        "name": "Saudi Riyal",
        "symbol_native": "ر.س.‏",
        "code": "SAR",
        "name_plural": "Saudi riyals",
        "flag": 'http://flags.fmcdn.net/data/flags/normal/za.png',
        "color":"blue"
},
{
        "id":"SDG" ,
        "symbol": "SDG",
        "name": "Sudanese Pound",
        "symbol_native": "SDG",
        "code": "SDG",
        "name_plural": "Sudanese pounds",
        "flag": "http://flags.fmcdn.net/data/flags/normal/sd.png",
        "color":"red"
},
{
        "id":"SEK" ,
        "symbol": "Skr",
        "name": "Swedish Krona",
        "symbol_native": "kr",
        "code": "SEK",
        "name_plural": "Swedish kronor",
        "flag": "http://flags.fmcdn.net/data/flags/normal/se.png",
        "color":"blue"
},
{
        "id":"SGD" ,
        "symbol": "S$",
        "name": "Singapore Dollar",
        "symbol_native": "$",
        "code": "SGD",
        "name_plural": "Singapore dollars",
        "flag":  "http://flags.fmcdn.net/data/flags/normal/sg.png",
        "color":"red"
},
{
        "id":"SOS" ,
        "symbol": "Ssh",
        "name": "Somali Shilling",
        "symbol_native": "Ssh",
        "code": "SOS",
        "name_plural": "Somali shillings",
        "flag": "http://flags.fmcdn.net/data/flags/normal/so.png",
        "color":"light-blue"
},
{
        "id":"SYP" ,
        "symbol": "SY£",
        "name": "Syrian Pound",
        "symbol_native": "ل.س.‏",
        "code": "SYP",
        "name_plural": "Syrian pounds",
        "flag": "http://flags.fmcdn.net/data/flags/normal/sy.png",
        "color":"red"
},
{
        "id":"THB",
        "symbol": "฿",
        "name": "Thai Baht",
        "symbol_native": "฿",
        "code": "THB",
        "name_plural": "Thai baht",
        "flag": "http://flags.fmcdn.net/data/flags/normal/th.png",
        "color":"red"
},
{
        "id":"TND" ,
        "symbol": "DT",
        "name": "Tunisian Dinar",
        "symbol_native": "د.ت.‏",
        "code": "TND",
        "name_plural": "Tunisian dinars",
        "flag": "http://flags.fmcdn.net/data/flags/normal/tn.png",
        "color":"red"
},
{
        "id":"TOP" ,
        "symbol": "T$",
        "name": "Tongan Paʻanga",
        "symbol_native": "T$",
        "code": "TOP",
        "name_plural": "Tongan paʻanga",
        "flag": "http://flags.fmcdn.net/data/flags/normal/to.png",
        "color":"red"
},
{
        "id":"TRY" ,
        "symbol": "TL",
        "name": "Turkish Lira",
        "symbol_native": "TL",
        "code": "TRY",
        "name_plural": "Turkish Lira",
        "flag": "http://flags.fmcdn.net/data/flags/normal/tr.png",
        "color":"red"
},
{
        "id":"TTD" ,
        "symbol": "TT$",
        "name": "Trinidad and Tobago Dollar",
        "symbol_native": "$",
        "code": "TTD",
        "name_plural": "Trinidad and Tobago dollars",
        "flag": "http://flags.fmcdn.net/data/flags/normal/tt.png",
        "color": "red"
},
{
        "id":"TWD" ,
        "symbol": "NT$",
        "name": "New Taiwan Dollar",
        "symbol_native": "NT$",
        "code": "TWD",
        "name_plural": "New Taiwan dollars",
        "flag": "http://flags.fmcdn.net/data/flags/normal/tw.png",
        "color":"red"
},
{
        "id":"TZS" ,
        "symbol": "TSh",
        "name": "Tanzanian Shilling",
        "symbol_native": "TSh",
        "code": "TZS",
        "name_plural": "Tanzanian shillings",
        "flag": "http://flags.fmcdn.net/data/flags/normal/tz.png",
        "color":"green",
},
{
        "id":"UAH" ,
        "symbol": "₴",
        "name": "Ukrainian Hryvnia",
        "symbol_native": "₴",
        "code": "UAH",
        "name_plural": "Ukrainian hryvnias",
        "flag": "http://flags.fmcdn.net/data/flags/normal/ua.png",
        "color":"blue",
},
{
        "id": "UGX",
        "symbol": "USh",
        "name": "Ugandan Shilling",
        "symbol_native": "USh",
        "code": "UGX",
        "name_plural": "Ugandan shillings",
        "flag": "http://flags.fmcdn.net/data/flags/normal/ug.png",
        "color":"yellow",
},
{
        "id":"UYU" ,
        "symbol": "$U",
        "name": "Uruguayan Peso",
        "symbol_native": "$",
        "code": "UYU",
        "name_plural": "Uruguayan pesos",
        "flag": "http://flags.fmcdn.net/data/flags/normal/uy.png",
        "color":"white",
},
{
        "id":"UZS",
        "symbol": "UZS",
        "name": "Uzbekistan Som",
        "symbol_native": "UZS",
        "code": "UZS",
        "name_plural": "Uzbekistan som",
        "flag": "http://flags.fmcdn.net/data/flags/normal/uz.png",
        "color":"light-blue",
},
{
        "id":"VEF" ,
        "symbol": "Bs.F.",
        "name": "Venezuelan Bolívar",
        "symbol_native": "Bs.F.",
        "code": "VEF",
        "name_plural": "Venezuelan bolívars",
        "flag": "http://flags.fmcdn.net/data/flags/normal/ve.png",
        "color":"yellow",
},{
        "id":"VND",
        "symbol": "₫",
        "name": "Vietnamese Dong",
        "symbol_native": "₫",
        "code": "VND",
        "name_plural": "Vietnamese dong",
        "flag": 'http://flags.fmcdn.net/data/flags/normal/vn.png',
        "color":"red",
},
{
        "id":"XAF" ,
        "symbol": "FCFA",
        "name": "CFA Franc BEAC",
        "symbol_native": "FCFA",
        "code": "XAF",
        "name_plural": "CFA francs BEAC",
        "flag": "http://flags.fmcdn.net/data/flags/normal/gn.png",
        "color":"yellow"
},
{
        "id":"XOF" ,
        "symbol": "CFA",
        "name": "CFA Franc BCEAO",
        "symbol_native": "CFA",
        "code": "XOF",
        "name_plural": "CFA francs BCEAO",
        "flag": 'http://flags.fmcdn.net/data/flags/normal/gw.png',
        "color":"red",
},{
        "id":"YER",
        "symbol": "YR",
        "name": "Yemeni Rial",
        "symbol_native": "ر.ي.‏",
        "code": "YER",
        "name_plural": "Yemeni rials",
        "flag": "http://flags.fmcdn.net/data/flags/normal/ye.png",
        "color":"red",
},
{
        "id":"ZMK",
        "symbol": "ZK",
        "name": "Zambian Kwacha",
        "symbol_native": "ZK",
        "code": "ZMK",
        "name_plural": "Zambian kwachas",
        "flag": "http://flags.fmcdn.net/data/flags/normal/zm.png",
        "color": "green",
},
]
export {currencyData, price}
